set -g mouse on
set -g history-limit 100000
set -g default-terminal "screen-256color"

set -g default-shell /usr/bin/fish
set -g default-command "fish"

# Bind Q to Kill-session
unbind Q
bind Q confirm-before -p "Kill session #S? (y/n)" kill-session

## bind ctrl+shift-left/right to swap window
bind-key -n C-S-Left swap-window -t -1\; select-window -t -1
bind-key -n C-S-Right swap-window -t +1\; select-window -t +1

# Copy from tmux-sensible
set -s escape-time 0
set -g display-time 4000
set -g status-interval 5
set -g focus-events on
set -g aggressive-resize on

# Better prefix using `
unbind C-b
set -g prefix `
bind ` send-prefix

set -g base-index 1
set -g pane-base-index 1
set-option -g renumber-windows on 

# Split window horizontal/vertical keybind
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Catppuccin configuration
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

set-option -g status-position top
set -g status-right-length 100
set -g status-left-length 100

## Left status bar
set -g @catppuccin_prefix_mode "#{?client_prefix,#[bg=#{@thm_red} fg=#{@thm_crust} bold] PREFIX #[default],#{?pane_in_mode,#[bg=#{@thm_yellow} fg=#{@thm_crust} bold] COPY #[default],#[bg=#{@thm_green} fg=#{@thm_crust} bold] NORMAL #[default]}}"
set -gF status-left "#{@catppuccin_prefix_mode}"
set -ag status-left " #[fg=#{@thm_fg} bold]TMUX (#S) "
set -g @catppuccin_window_default_fill "number"
set -g @catppuccin_window_current_fill "number"
set -g @catppuccin_window_current_text " #{=/-32/...:#{s|$HOME|~|:pane_current_path}} "

## Right status bar
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"

## Seperators
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_connect_separator "no"

#Vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

## display menu for common shortcuts (Don't overpack this)
bind-key m display-menu -x R -y P \
    "󰆍 Reload Config" r "source-file ~/.config/tmux/tmux.conf" \
    "󰩈 New Window" c "new-window" \
    "󰗼 Kill Pane" x "kill-pane" \
    "󰀂 Swap Window ←/→ (C-S-Left/Right)" "" "" \
    "󰑕 Rename Window" "," "command-prompt -I '#W' 'rename-window -- %%'" \
    "󰓦 Sync Panes (toggle)" S "set-window-option synchronize-panes" \
    "󰐥 Kill Server" Q "kill-server" 

## Manual reload source-file
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded"

run '~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux'

## Make background transparent
set -g status-style "bg=terminal"
